name: testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6, 3.8]
        cpp-version: [gcc-5, clang-3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
    - name: Configuring Test Environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ipython nbval pytest-xdist cython
        sudo apt install libatlas-base-dev g++ clang++
    - name: Setup
      run: python setup.py install
